---
- hosts: all
  vars:
    ansible_ssh_pass: "{{ lookup('file', '~/.rootpassword') }}"
  tasks:
    - name: Push rsa public key to all machines
      authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', '~/.ssh/paas.pub') }}"
