---
- name: Update k8s nodes conf
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - src: "config.j2"
      dest: "/etc/kubernetes/config"
    - src: "kubelet.j2"
      dest: "/etc/kubernetes/kubelet"
    - src: "td-agent.conf.j2"                                                       
      dest: "/etc/td-agent/td-agent.conf"                                           
  notify:
    - restart kubelet and kube-proxy 
