---
- name: Stop k8s master  
  service: name={{ item }} state=stopped
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Update k8s bin 
  shell: RSYNC_PASSWORD=paasci rsync -av paasci@{{ rsync_server }}::{{ k8s_rsync_repo }} /usr/bin/
  ignore_errors: yes

- name: Start k8s master  
  service: name={{ item }} state=started
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
